import { initializeApp } from "firebase/app";
import { getAuth } from "firebase/auth";
import { getFirestore, collection, getDocs } from "firebase/firestore";
// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional

const firebaseConfig = {
  apiKey: import.meta.env.VITE_FIREBASE_API_KEY,
  authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
  projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID,
  storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
  appId: import.meta.env.VITE_FIREBASE_APP_ID,
  measurementId: import.meta.env.VITE_FIREBASE_MEASUREMENT_ID,
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);

export const auth = getAuth(app);
export const apiKey = firebaseConfig.apiKey;
export const db = getFirestore(app);

export const getHotelsFromFirebase = async () => {
  const snapshot = await getDocs(collection(db, "hotels"));

  const hotels = snapshot.docs.map((doc) => ({
    id: doc.id,
    ...doc.data(),
  }));

  return hotels;
};

export const DUMMY_HOTELS = [
  {
    id: "h1",
    name: "Hotel Blue Lagoon",
    city: "Pune",
    address: "MG Road, Pune",
    stars: 4,
    propertyType: "Hotel",
    features: ["Breakfast included", "Free cancellation", "Parking available"],
    rating: 8.7,
    reviews: 152,
    guests: 1,
    nights: 1,
    originalPrice: 12000,
    offerPrice: 7200,
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&auto=format&fit=crop",
    ],
  },
  {
    id: "h2",
    name: "The Grand Residency",
    city: "Mumbai",
    address: "Bandra West, Mumbai",
    stars: 5,
    propertyType: "Hotel",
    features: ["All meals included", "Swimming pool", "Free cancellation"],
    rating: 9.1,
    reviews: 320,
    guests: 1,
    nights: 1,
    originalPrice: 20000,
    offerPrice: 13500,
    images: [
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&auto=format&fit=crop",
    ],
  },
  {
    id: "h3",
    name: "Ocean View Suites",
    city: "Mumbai",
    address: "Marine Drive, Mumbai",
    stars: 4,
    propertyType: "Apartment",
    features: ["Sea view", "Breakfast included", "Parking available"],
    rating: 8.3,
    reviews: 210,
    guests: 1,
    nights: 1,
    originalPrice: 18000,
    offerPrice: 9900,
    images: [
      "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&auto=format&fit=crop",
    ],
  },
  {
    id: "h4",
    name: "Breeze Residency",
    city: "Pune",
    address: "Koregaon Park, Pune",
    stars: 3,
    propertyType: "Hotel",
    features: ["Free Wi-Fi", "Breakfast included", "Pet friendly"],
    rating: 7.8,
    reviews: 88,
    guests: 1,
    nights: 1,
    originalPrice: 8000,
    offerPrice: 5200,
    images: [
      "https://images.unsplash.com/photo-1501117716987-c8e6be4d2b0b?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1533055640609-24b498cdfe0b?w=600&auto=format&fit=crop",
    ],
  },
  {
    id: "h5",
    name: "Palm Residency",
    city: "Bangalore",
    address: "Indiranagar, Bangalore",
    stars: 5,
    propertyType: "Hotel",
    features: ["All meals included", "Luxury Spa", "Pet friendly"],
    rating: 8.5,
    reviews: 145,
    guests: 1,
    nights: 1,
    originalPrice: 11000,
    offerPrice: 7200,
    images: [
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600&auto=format&fit=crop",
    ],
  },
  {
    id: "h6",
    name: "Hotel Aura Palace",
    city: "New Delhi",
    address: "Paharganj, New Delhi",
    stars: 5,
    propertyType: "Hotel",
    features: ["Breakfast & Dinner included", "Swimming pool", "Parking"],
    rating: 7.2,
    reviews: 65,
    guests: 1,
    nights: 1,
    originalPrice: 7990,
    offerPrice: 5990,
    images: [
      "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=600&auto=format&fit=crop",
    ],
  },
  {
    id: "h7",
    name: "JS Residency Suites",
    city: "New Delhi",
    address: "Nizamuddin, New Delhi",
    stars: 4,
    propertyType: "Hotel",
    features: ["Free Wi-Fi", "Breakfast included", "Parking available"],
    rating: 9.8,
    reviews: 402,
    guests: 1,
    nights: 1,
    originalPrice: 36800,
    offerPrice: 18400,
    images: [
      "https://images.unsplash.com/photo-1559508551-44bff1de756b?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1611048267451-e6ed903d4a38?w=600&auto=format&fit=crop",
    ],
  },
  {
    id: "h8",
    name: "Houseboat Kerala Dream",
    city: "Kochi",
    address: "Backwaters, Kochi",
    stars: 4,
    propertyType: "Houseboat",
    features: ["All meals included", "Private deck", "Free cancellation"],
    rating: 8.9,
    reviews: 112,
    guests: 1,
    nights: 1,
    originalPrice: 16000,
    offerPrice: 11200,
    images: [
      "https://images.unsplash.com/photo-1544986581-efac024faf62?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&auto=format&fit=crop",
    ],
  },
  {
    id: "h9",
    name: "Villa Serenity",
    city: "Goa",
    address: "Candolim Beach, Goa",
    stars: 5,
    propertyType: "Villa",
    features: ["Private pool", "Parking available", "All meals included"],
    rating: 9.6,
    reviews: 188,
    guests: 1,
    nights: 1,
    originalPrice: 28000,
    offerPrice: 21000,
    images: [
      "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1575517111478-7f6afd0973db?w=600&auto=format&fit=crop",
    ],
  },
  {
    id: "h10",
    name: "Seaside Apartment",
    city: "Mumbai",
    address: "Juhu Beach, Mumbai",
    stars: 4,
    propertyType: "Apartment",
    features: ["Sea view", "Breakfast included", "Free cancellation"],
    rating: 8.1,
    reviews: 95,
    guests: 1,
    nights: 1,
    originalPrice: 15000,
    offerPrice: 10500,
    images: [
      "https://images.unsplash.com/photo-1526779259212-2f7385bbdb7e?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1529101091764-c3526daf38fe?w=600&auto=format&fit=crop",
    ],
  },
  {
    id: "h11",
    name: "Homestay Harmony",
    city: "Shimla",
    address: "Mall Road, Shimla",
    stars: 4,
    propertyType: "Apartment",
    features: ["Breakfast included", "Free Wi-Fi", "Parking available"],
    rating: 8.5,
    reviews: 110,
    guests: 1,
    nights: 1,
    originalPrice: 9000,
    offerPrice: 6400,
    images: [
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=600&auto=format&fit=crop",
    ],
  },
  {
    id: "h12",
    name: "Guesthouse Sunrise",
    city: "Jaipur",
    address: "Pink City, Jaipur",
    stars: 3,
    propertyType: "Guesthouse",
    features: ["Breakfast included", "Free Wi-Fi", "No prepayment needed"],
    rating: 7.9,
    reviews: 76,
    guests: 1,
    nights: 1,
    originalPrice: 5500,
    offerPrice: 3900,
    images: [
      "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1544148103-0773bf10d330?w=600&auto=format&fit=crop",
    ],
  },
  {
    id: "h13",
    name: "Royal Palace Hotel",
    city: "New Delhi",
    address: "Connaught Place, New Delhi",
    stars: 5,
    propertyType: "Hotel",
    features: ["Luxury spa", "Breakfast included", "Swimming pool"],
    rating: 9.0,
    reviews: 210,
    guests: 1,
    nights: 1,
    originalPrice: 25000,
    offerPrice: 18500,
    images: [
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600&auto=format&fit=crop",
    ],
  },
  {
    id: "h14",
    name: "Sunset Villa",
    city: "Goa",
    address: "Baga Beach, Goa",
    stars: 4,
    propertyType: "Villa",
    features: ["Private pool", "Beach view", "Breakfast included"],
    rating: 8.8,
    reviews: 142,
    guests: 1,
    nights: 1,
    originalPrice: 23000,
    offerPrice: 16800,
    images: [
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=600&auto=format&fit=crop",
    ],
  },
  {
    id: "h15",
    name: "Mountain View Inn",
    city: "Shimla",
    address: "The Ridge, Shimla",
    stars: 3,
    propertyType: "Guesthouse",
    features: ["Mountain view", "Breakfast included", "Free Wi-Fi"],
    rating: 7.5,
    reviews: 68,
    guests: 1,
    nights: 1,
    originalPrice: 6000,
    offerPrice: 4300,
    images: [
      "https://images.unsplash.com/photo-1551882540-17b6ed7193c0?w=600&auto=format&fit=crop",
    ],
  },
  {
    id: "h16",
    name: "City Center Hotel",
    city: "Bangalore",
    address: "MG Road, Bangalore",
    stars: 4,
    propertyType: "Hotel",
    features: ["Free Wi-Fi", "Parking available", "Breakfast included"],
    rating: 8.2,
    reviews: 123,
    guests: 1,
    nights: 1,
    originalPrice: 10000,
    offerPrice: 7500,
    images: [
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=600&auto=format&fit=crop",
    ],
  },
  {
    id: "h17",
    name: "Backwater Houseboat",
    city: "Kochi",
    address: "Alleppey, Kochi",
    stars: 4,
    propertyType: "Houseboat",
    features: ["Private deck", "Breakfast included", "Fishing deck"],
    rating: 8.6,
    reviews: 95,
    guests: 1,
    nights: 1,
    originalPrice: 14500,
    offerPrice: 11000,
    images: [
      "https://images.unsplash.com/photo-1544986581-efac024faf62?w=600&auto=format&fit=crop",
    ],
  },
  {
    id: "h18",
    name: "Beachside Hotel",
    city: "Goa",
    address: "Calangute Beach, Goa",
    stars: 4,
    propertyType: "Hotel",
    features: ["Breakfast included", "Beach view", "Free Wi-Fi"],
    rating: 8.0,
    reviews: 104,
    guests: 1,
    nights: 1,
    originalPrice: 20000,
    offerPrice: 15000,
    images: [
      "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=600&auto=format&fit=crop",
    ],
  },
  {
    id: "h19",
    name: "Downtown Apartment",
    city: "Mumbai",
    address: "Lower Parel, Mumbai",
    stars: 4,
    propertyType: "Apartment",
    features: ["City view", "Breakfast included", "Free cancellation"],
    rating: 8.4,
    reviews: 132,
    guests: 1,
    nights: 1,
    originalPrice: 17000,
    offerPrice: 11500,
    images: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&auto=format&fit=crop",
    ],
  },
  {
    id: "h20",
    name: "Serene Stay",
    city: "Bangalore",
    address: "Whitefield, Bangalore",
    stars: 5,
    propertyType: "Hotel",
    features: ["Swimming pool", "Spa", "Breakfast included"],
    rating: 9.2,
    reviews: 210,
    guests: 1,
    nights: 1,
    originalPrice: 22000,
    offerPrice: 17500,
    images: [
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=600&auto=format&fit=crop",
    ],
  },

  // 5 new hotels to make total 25
  {
    id: "h21",
    name: "Paradise Resort",
    city: "Jaipur",
    address: "Amber Fort Road, Jaipur",
    stars: 5,
    propertyType: "Resort",
    features: ["Swimming pool", "All meals included", "Spa"],
    rating: 9.3,
    reviews: 178,
    guests: 1,
    nights: 1,
    originalPrice: 26000,
    offerPrice: 19500,
    images: [
      "https://images.unsplash.com/photo-1576675786759-81c0bb0d7c4b?w=600&auto=format&fit=crop",
    ],
  },
  {
    id: "h22",
    name: "Hilltop Villa",
    city: "New Delhi",
    address: "Mehrauli, New Delhi",
    stars: 4,
    propertyType: "Villa",
    features: ["Private pool", "Breakfast included", "Parking available"],
    rating: 8.7,
    reviews: 120,
    guests: 1,
    nights: 1,
    originalPrice: 24000,
    offerPrice: 18000,
    images: [
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600&auto=format&fit=crop",
    ],
  },
  {
    id: "h23",
    name: "Oceanfront Guesthouse",
    city: "Goa",
    address: "Vagator Beach, Goa",
    stars: 3,
    propertyType: "Guesthouse",
    features: ["Breakfast included", "Sea view", "Free Wi-Fi"],
    rating: 7.9,
    reviews: 85,
    guests: 1,
    nights: 1,
    originalPrice: 7000,
    offerPrice: 5000,
    images: [
      "https://images.unsplash.com/photo-1560343090-f0409e92791a?w=600&auto=format&fit=crop",
    ],
  },
  {
    id: "h24",
    name: "Royal Beach Resort",
    city: "Mumbai",
    address: "Juhu Beach, Mumbai",
    stars: 5,
    propertyType: "Resort",
    features: ["Private beach", "All meals included", "Spa"],
    rating: 9.4,
    reviews: 210,
    guests: 1,
    nights: 1,
    originalPrice: 30000,
    offerPrice: 22000,
    images: [
      "https://images.unsplash.com/photo-1526662096691-4ab3f9a4c8f7?w=600&auto=format&fit=crop",
    ],
  },
  {
    id: "h25",
    name: "Green Valley Guesthouse",
    city: "Bangalore",
    address: "Kanakapura Road, Bangalore",
    stars: 3,
    propertyType: "Guesthouse",
    features: ["Breakfast included", "Free Wi-Fi", "Garden view"],
    rating: 7.8,
    reviews: 90,
    guests: 1,
    nights: 1,
    originalPrice: 6500,
    offerPrice: 4800,
    images: [
      "https://images.unsplash.com/photo-1560343090-f0409e92791a?w=600&auto=format&fit=crop",
    ],
  },
];
